# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://mazhuang.org
date_format: "ordinal"
title: Keke Hu's Personal Website
subtitle: "I'm the top machine learning scientist!"
description: "Computer Scientist's Personal Website"
keywords: Keke Hu, Computer Scientist, Personal Website
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Computer Scientist
organization: Shanghai Jiaotong University
organization_url: http://www.sjtu.edu.cn/
location: Shanghai, China
email: TODO

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: artificialintelligencecn/artificialintelligencecn.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: artificialintelligencecn
douban_username: artificialintelligencecn
facebook_username: artificialintelligencecn
weibo_username: artificialintelligencecn
zhihu_username: artificialintelligencecn
twitter_username: artificialintelligencecn

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: 邱学家
disqus_username: computersicentist
# 在使用一个时可点击显示另一个
lazy_load_another : true



# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
